In [2]:
import pandas as pd
import numpy as np


pd.set_option('display.max_columns', None)
pd.set_option('display.width', None) 
pd.set_option('display.max_colwidth', 10)

1. Carga e inspección

In [3]:
df = pd.read_csv('laptopData.csv')
df.head()

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0.0,Apple,Ultrabook,13.3,IPS Pa...,Intel ...,8GB,128GB SSD,Intel ...,macOS,1.37kg,71378....
1,1.0,Apple,Ultrabook,13.3,1440x900,Intel ...,8GB,128GB ...,Intel ...,macOS,1.34kg,47895....
2,2.0,HP,Notebook,15.6,Full H...,Intel ...,8GB,256GB SSD,Intel ...,No OS,1.86kg,30636....
3,3.0,Apple,Ultrabook,15.4,IPS Pa...,Intel ...,16GB,512GB SSD,AMD Ra...,macOS,1.83kg,135195...
4,4.0,Apple,Ultrabook,13.3,IPS Pa...,Intel ...,8GB,256GB SSD,Intel ...,macOS,1.37kg,96095....

In [4]:
df.shape

(1303, 12)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1273 non-null   float64
 1   Company           1273 non-null   object
 2   TypeName          1273 non-null   object
 3   Inches            1273 non-null   object
 4   ScreenResolution  1273 non-null   object
 5   Cpu               1273 non-null   object
 6   Ram               1273 non-null   object
 7   Memory            1273 non-null   object
 8   Gpu               1273 non-null   object
 9   OpSys             1273 non-null   object
 10  Weight            1273 non-null   object
 11  Price             1273 non-null   float64
dtypes: float64(2), object(10)
memory usage: 122.3+ KB

In [6]:
print(df.columns)
df.head()

Index(['Unnamed: 0', 'Company', 'TypeName', 'Inches', 'ScreenResolution',
       'Cpu', 'Ram', 'Memory', 'Gpu', 'OpSys', 'Weight', 'Price'],
      dtype='object')

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0.0,Apple,Ultrabook,13.3,IPS Pa...,Intel ...,8GB,128GB SSD,Intel ...,macOS,1.37kg,71378....
1,1.0,Apple,Ultrabook,13.3,1440x900,Intel ...,8GB,128GB ...,Intel ...,macOS,1.34kg,47895....
2,2.0,HP,Notebook,15.6,Full H...,Intel ...,8GB,256GB SSD,Intel ...,No OS,1.86kg,30636....
3,3.0,Apple,Ultrabook,15.4,IPS Pa...,Intel ...,16GB,512GB SSD,AMD Ra...,macOS,1.83kg,135195...
4,4.0,Apple,Ultrabook,13.3,IPS Pa...,Intel ...,8GB,256GB SSD,Intel ...,macOS,1.37kg,96095....

In [7]:
df.rename(columns={'Unnamed: 0': 'id', 'Company': 'compania', 'TypeName': 'tipo_laptop', 'Inches': 'pulgadas', 'ScreenResolution': 'resolucion_pantalla', 'Cpu': 'procesador', 'Gpu': 'tarjeta_grafica', 'OpSys': 'sistema_operativo', 'Weight': 'peso', 'Price': 'precio'}, inplace=True)

In [8]:
df.rename(columns={'Memory': 'memoria'}, inplace=True)

In [9]:
df.head()

,id,compania,tipo_laptop,pulgadas,resolucion_pantalla,procesador,Ram,memoria,tarjeta_grafica,sistema_operativo,peso,precio
0,0.0,Apple,Ultrabook,13.3,IPS Pa...,Intel ...,8GB,128GB SSD,Intel ...,macOS,1.37kg,71378....
1,1.0,Apple,Ultrabook,13.3,1440x900,Intel ...,8GB,128GB ...,Intel ...,macOS,1.34kg,47895....
2,2.0,HP,Notebook,15.6,Full H...,Intel ...,8GB,256GB SSD,Intel ...,No OS,1.86kg,30636....
3,3.0,Apple,Ultrabook,15.4,IPS Pa...,Intel ...,16GB,512GB SSD,AMD Ra...,macOS,1.83kg,135195...
4,4.0,Apple,Ultrabook,13.3,IPS Pa...,Intel ...,8GB,256GB SSD,Intel ...,macOS,1.37kg,96095....

In [10]:
df.isna().sum()

id                     30
compania               30
tipo_laptop            30
pulgadas               30
resolucion_pantalla    30
procesador             30
Ram                    30
memoria                30
tarjeta_grafica        30
sistema_operativo      30
peso                   30
precio                 30
dtype: int64

In [11]:
df['precio'].describe(include='all')

count    1273.0...
mean     59955....
std      37332....
min      9270.7...
25%      31914....
50%      52161....
75%      79333....
max      324954...
Name: precio, dtype: float64

2. Limpieza y transformacioiin basica

In [12]:
df.isna().sum()

id                     30
compania               30
tipo_laptop            30
pulgadas               30
resolucion_pantalla    30
procesador             30
Ram                    30
memoria                30
tarjeta_grafica        30
sistema_operativo      30
peso                   30
precio                 30
dtype: int64

In [13]:
##Elimino la columna id porque no aporta nada a mi análisis y tiene muchos valores nulos.
df.drop('id', axis=1, inplace=True, errors='ignore')

In [14]:
##Eliminamos todas las filas que contienen valores nulos, ya que no son muchas y no queremos imputar datos.
df.dropna(inplace=True)

In [30]:
pulgadas = df['pulgadas'].unique()
print(pulgadas)

['13.3' '15.6' '15.4' '14' '12' '17.3' '13.5' '12.5' '13' '18.4' '13.9'
 '11.6' '25.6' '35.6' '12.3' '27.3' '24' '33.5' '31.6' '17' '15' '14.1'
 '11.3' '10.1']

In [ ]:
###Resultado del codigo anterior antes de reemplazar el valor '?':

###['13.3' '15.6' '15.4' '14' '12' '17.3' '13.5' '12.5' '13' '18.4' '13.9'
###'11.6' '25.6' '35.6' '12.3' '27.3' '24' '33.5' '?' '31.6' '17' '15'
###'14.1' '11.3' '10.1']

In [28]:
df[df['pulgadas'] == '?']

Empty DataFrame
Columns: [compania, tipo_laptop, pulgadas, resolucion_pantalla, procesador, Ram, memoria, tarjeta_grafica, sistema_operativo, peso, precio]
Index: []

In [ ]:
	###Resultado: 1 fila con valor '?', que corresponde a un Dell Precision 7520 FHD 15.6" Workstation Business PC (Intel Quad Core i7-7700HQ, 16GB Ram, 256GB SSD, Thunderbolt 3) Nvidia Quadro M1200 4GB DDR5. Por lo tanto, reemplazamos el valor '?' por '15.6', que es el tamaño de pantalla de ese modelo.

     ##compania	tipo_laptop	pulgadas	resolucion_pantalla	procesador	Ram	memoria	tarjeta_grafica	sistema_operativo	peso	precio
###476	Dell	Workst...	?	Full H...	Intel ...	8GB	256GB SSD	Nvidia...	Window...	1.78kg	128298.24

In [29]:
###Dell Precision 7520 FHD 15.6" Workstation Business PC (Intel Quad Core i7-7700HQ, 16GB Ram, 256GB SSD, Thunderbolt 3) Nvidia Quadro M1200 4GB DDR5
df['pulgadas'] = df['pulgadas'].str.replace('?', '15.6', regex=False)

In [ ]:
###Podria colocar Unknown o Desconocido, pero no lo hago porque las configuraciones de los equipos son diferentees y afectarian el analisis

##df['compania'].fillna('unknown', inplace=True)
##df['tipo_laptop'].fillna('unknown', inplace=True)
##df['pulgadas'].fillna('unknown', inplace=True)
##df['resolucion'].fillna('unknown', inplace=True)
##df['procesador'].fillna('unknown', inplace=True)
##df['tarjeta_grafica'].fillna('unknown', inplace=True)
##df['sistema_operativo'].fillna('unknown', inplace=True)
##df['peso'].fillna('unknown', inplace=True)
## df['precio'].fillna('unknown', inplace=True)

In [20]:
df['tipo_laptop'].value_counts()

tipo_laptop
Notebook              710
Gaming                203
Ultrabook             191
2 in 1 Convertible    116
Workstation            29
Netbook                24
Name: count, dtype: int64

In [21]:
##Corregimos el error de tipeo en la columna tipo_laptop, cambiando Netbook por Notebook
df['tipo_laptop'] = df['tipo_laptop'].str.replace('Netbook', 'Notebook', regex=False)

In [22]:
df['compania'].value_counts()

compania
Lenovo       290
Dell         287
HP           266
Asus         156
Acer         103
MSI           53
Toshiba       47
Apple         21
Samsung        9
Mediacom       7
Razer          7
Microsoft      6
Vero           4
Xiaomi         4
Chuwi          3
LG             3
Google         3
Huawei         2
Fujitsu        2
Name: count, dtype: int64

In [23]:
##Cambiamos la referncia de Vero por Acer, ya que es un error de tipeo y no existe la marca Vero y es una linea de la marca Acer
df['compania'] = df['compania'].str.replace('Vero', 'Acer', regex=False)

In [24]:
##Miramos si hay filas duplicadas, ya que pueden sesgar nuestro análisis y no aportan nada nuevo.
df.duplicated().sum()

np.int64(29)

In [25]:
#Eliminamos las filas duplicadas, ya que no aportan nada nuevo a nuestro análisis y pueden sesgar los resultados.
df.drop_duplicates(inplace=True)

In [26]:
df['memoria'].value_counts()

memoria
256GB SSD                        401
1TB HDD                          209
500GB HDD                        121
512GB SSD                        112
128GB SSD +  1TB HDD              92
128GB SSD                         72
256GB SSD +  1TB HDD              71
32GB Flash Storage                35
2TB HDD                           16
512GB SSD +  1TB HDD              14
1TB SSD                           13
64GB Flash Storage                12
256GB SSD +  2TB HDD              10
256GB Flash Storage                8
16GB Flash Storage                 7
1.0TB Hybrid                       7
32GB SSD                           6
128GB Flash Storage                4
180GB SSD                          4
16GB SSD                           3
512GB SSD +  2TB HDD               3
256GB SSD +  500GB HDD             2
128GB SSD +  2TB HDD               2
256GB SSD +  256GB SSD             2
1TB SSD +  1TB HDD                 2
512GB Flash Storage                2
512GB SSD +  512GB SSD             1
64GB SSD                           1
64GB Flash Storage +  1TB HDD      1
1TB HDD +  1TB HDD                 1
32GB HDD                           1
512GB SSD +  256GB SSD             1
?                                  1
128GB HDD                          1
240GB SSD                          1
8GB SSD                            1
508GB Hybrid                       1
1.0TB HDD                          1
512GB SSD +  1.0TB Hybrid          1
256GB SSD +  1.0TB Hybrid          1
Name: count, dtype: int64

In [36]:
df[df['pulgadas'] == '25.6']

,compania,tipo_laptop,pulgadas,resolucion_pantalla,procesador,Ram,memoria,tarjeta_grafica,sistema_operativo,peso,precio
402,Lenovo,Notebook,25.6,IPS Pa...,Intel ...,8GB,256GB ...,AMD Ra...,Window...,2.1kg,60978.96